services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sqs,dynamodb,s3
    ports:
      - "4566:4566"

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "8000:8000"
    depends_on:
      - localstack

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      - localstack
